tasks = [
    ("../demos/lexbor/lib.db", ["document.h", "parser.h", "unicode.h"], [
        ("lxb_html_parser_init", ("!=", "0")),
        ("lxb_html_parser_destroy", ("!", "NULL")),
        ("lxb_html_parser_ref", ("!", "NULL")),
        ("lxb_html_parser_unref", ("!", "NULL")),
        ("lxb_html_parse", ("!", "NULL")),
        ("lxb_html_parse_fragment", ("!", "NULL")),
        ("lxb_html_parse_fragment_by_tag_id", ("!", "NULL")),
        ("lxb_html_parse_fragment_chunk_begin", ("!=", "0")),
        ("lxb_html_parse_fragment_chunk_process", ("!=", "0")),
        ("lxb_html_parse_fragment_chunk_end", ("!", "NULL")),
        ("lxb_html_parse_chunk_begin", ("!", "NULL")),
        ("lxb_html_parse_chunk_process", ("!=", "0")),
        ("lxb_html_parse_chunk_end", ("!=", "0")),
        ("lxb_html_parser_tree_noi", ("!", "NULL")),
        ("lxb_html_parser_status_noi", ("!=", "0")),
        ("lxb_html_parser_scripting_noi", (">", "0")),
        ("lxb_unicode_idna_type", ("!=", "0")),
        ("lexbor_mem_init", "[2, 3] U [9, 9]"),
        ("lexbor_bst_init", ""),
        ("lexbor_array_obj_destroy", ("==", "NULL")),
        ("lexbor_avl_init", ("!=", 0)),
        ("lexbor_avl_foreach", ("!=", 0)),
        ("lexbor_array_obj_expand", ("==", "NULL")),
        ("lexbor_array_obj_push",("==", "NULL")),
        ("lexbor_array_obj_pop", ("==", "NULL")),
        ("lexbor_array_init", "[2, 3] U [5, 5]"),
        ("lxb_html_tokenizer_state_to_ascii_utf_8", ("==", "0")),
    ]),
]

